Repository Artifact-Works/GeomCpp, pull requests merged in 2025-02, with the labels that each got.

#17 [Feat] Point Arithmetic: Subtraction. Issue : #4 (jwoc - 1)
  Core/Point.hpp
Labels: Easy, JWOC, Feature addition

#18 Added Operation/ and passed Unit tests
  Core/Point.hpp
  tests/test_point.cpp
Labels: Easy, JWOC, Feature addition, Under Testing

#24 Created .gitignore
  .gitignore
Labels: Easy, JWOC

#22 Implement point magnitude
  Core/Point.hpp
  tests/test_point.cpp
Labels: Easy, JWOC

#19 Added reflection (2D/3D) and passed unit tests
  .gitignore
  Core/Point.hpp
  tests/test_point.cpp
Labels: Hard, JWOC, Under Testing
